require 'rubygems'
require 'em-zeromq'
require 'eventmachine'
require 'dante'
require 'socket'
require 'pp'
require 'json'
require 'uuid'

require 'collectd-zmq/local_collectd_handler'
require 'collectd-zmq/test_zmq_handler'
